version: '3.1'
services:
  odoo:
    image: odoo:16.0
    container_name: odoo
    depends_on:
      - db
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./odoo/odoo.conf:/etc/odoo/odoo.conf
      - ./odoo/addons:/mnt/extra-addons
    environment:
      - PASSWORD=my-odoo-db-password
      - USER=odoo
      - HOST=db
    restart: always
  db:
    image: postgres:15
    container_name: odoo_db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=my-odoo-db-password
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    restart: always

volumes:
  odoo-data:
  odoo-db-data:
